### ISSUE TITLE
It now compiles, gets exported correctly, loaded, initialised, and crashes :)

### ISSUE THREAD

**Issue by BastiaanOlij** [GodotVR/godot_gearvr#18]
Hey Paritosh,

Seeing your phone probably doesn't get this far, this is whats written to the logs:
```
06-29 20:44:00.538 10210 10227 I godot   : ==============================================================
06-29 20:44:00.538 10210 10227 I VrAppLoader: VrApi Loader Version: 1.1.14.0-0-0 Apr 16 2018 13:10:58
06-29 20:44:00.543 10210 10227 V VrDriver: Loading 32-bit VrDriver...
06-29 20:44:00.548 10210 10227 W System.err: java.lang.RuntimeException: Requested VrApi version (api=1.1.14.0, driver=0) is incompatible with the currently installed version.
06-29 20:44:00.548 10210 10227 W System.err:    at com.oculus.systemdriver.DriverLoader.loadInternal(DriverLoader.java:118)
06-29 20:44:00.548 10210 10227 W System.err:    at com.oculus.systemdriver.DriverLoader.load32(DriverLoader.java:239)
06-29 20:44:00.548 10210 10227 W System.err:    at org.godotengine.godot.GodotLib.step(Native Method)
06-29 20:44:00.548 10210 10227 W System.err:    at org.godotengine.godot.GodotView$Renderer.onDrawFrame(GodotView.java:666)
06-29 20:44:00.548 10210 10227 W System.err:    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1649)
06-29 20:44:00.548 10210 10227 W System.err:    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1354)
06-29 20:44:00.548 10210 10227 W VrAppLoader: vrapi_Initialize: Failed to load VrApi driver! Java Exception
06-29 20:44:00.548 10210 10227 W System.err: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
06-29 20:44:00.548 10210 10227 W System.err:    at android.app.ContextImpl.startActivity(ContextImpl.java:734)
06-29 20:44:00.548 10210 10227 W System.err:    at android.app.ContextImpl.startActivity(ContextImpl.java:721)
06-29 20:44:00.548 10210 10227 W System.err:    at android.content.ContextWrapper.startActivity(ContextWrapper.java:345)
06-29 20:44:00.548 10210 10227 W System.err:    at org.godotengine.godot.GodotLib.step(Native Method)
06-29 20:44:00.548 10210 10227 W System.err:    at org.godotengine.godot.GodotView$Renderer.onDrawFrame(GodotView.java:666)
06-29 20:44:00.548 10210 10227 W System.err:    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1649)
06-29 20:44:00.548 10210 10227 W System.err:    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1354)
06-29 20:44:00.548 10210 10227 E VrAppLoader: DisplayErrorAndExit: Failed to launch SystemActivities
06-29 20:44:00.548 10210 10227 I art     : System.exit called, status: 0
06-29 20:44:00.548 10210 10227 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
```

So the "================================" I add right before initialising, after that you can see that it calls VrAppLoader and getting feedback about the version, so it's getting pretty far.

It then crashes on an incompatible version error... Now that could very well be because my note 4 is running a pretty old version of gearvr.

All in all, I call that a breakthrough my friend.

**Comment by Paritosh97** [comment]
I think it's fixed in #17 and can be closed.
